[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.135.0"   # use the latest stable release
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
